version: '3'

vars:
  GREETING: Hello, World!
  ENTRYPOINT: src/argus/main.py
  VENV: poetry env info --path

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
  api:
    cmds:
      - poetry run fastapi dev src/argus/main.py --reload
  client:
    cmds:
      - streamlit run ui/entrypoint.py
  test:
    cmds:
      - poetry run pytest # unit test
      - poetry run mypy src/argus # type checker
      - poetry run ruff format src/ tests/ --check # linter and formatter
      - poetry run ruff check src/ tests/ --select I,F,S,W,E # linter and formatter
  format:
    cmds:
      - poetry run ruff format src/ tests/
