version: '3'

vars:
  GREETING: Hello, World!
  ENTRYPOINT: app/main.py
  VENV: poetry env info --path

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  run-local:
    cmds:
      - fastapi dev "{{.ENTRYPOINT}}"
  test:
    cmds:
      - pylint app/** # style
      - mypy app # type checker
      - pytest # unit test
