version: '3'

vars:
  GREETING: Hello, World!
  ENTRYPOINT: app/main.py
  VENV: poetry env info --path

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
  api:
    cmds:
      - uvicorn app.main:app --reload
  client:
    cmds:
      - streamlit run ui/entrypoint.py
  test:
    cmds:
      - ruff check # linter and formatter
      - mypy app # type checker
      - pytest # unit test
  format:
    cmds:
      - ruff format
